<?php

/**
 * Auto-generated by JavascriptClassBundle.
 * This is the Base Controller Class for AntController
 * It holds the Javascript-related mapping and data identifying the PHP Entity used
 *
 * YOU SHOULD NOT EDIT THIS FILE
 */

namespace Nutellove\JavascriptClassBundle\Controller\Entity\JavascriptClassBundle\Base;

use Nutellove\JavascriptClassBundle\Controller\AbstractEntityController;

class AntController extends AbstractEntityController
{

  public function getBundleName()
  {
    return 'JavascriptClassBundle';
  }


  public function getEntityName()
  {
    return 'Ant';
  }


  public function getJavascriptMapping()
  {
    static $map;
    if (!$map){
      $map = array (
        'id' => array (
          'read'  => true,
          'write' => false,
          'role'  => 'parameter'
        ),
        'name' => array (
          'read'  => true,
          'write' => false,
          'role'  => 'parameter'
        ),
        'is_hungry' => array (
          'read'  => true,
          'write' => true,
          'role'  => 'parameter'
        ),
      );
    }
    return $map;
  }

}
